# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('Under 18', 'Under 18'), ('18-19', '18-19'), ("20's", "20's"), ("30's", "30's"), ("40's", "40's"), ("50's", "50's"), ('60+', '60+')], default="20's", max_length=8),
        ),
    ]
