# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20160401_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=40)),
                ('skill', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sportsmanship', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('punctuality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_feedbacks', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
