# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HendersonPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('img_url', models.URLField(blank=True, max_length=350, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modifided_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='parks',
            field=models.ManyToManyField(to='skill_match.HendersonPark'),
        ),
    ]
