# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Pickleball', 'Pickleball'), ('Other', 'Other')], max_length=25)),
                ('other', models.CharField(blank=True, max_length=25, null=True)),
                ('img_url', models.URLField(default='http://res.cloudinary.com/skill-match/image/upload/v1451804013/trophy_200_cnaras.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hendersonpark',
            old_name='modifided_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='court',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_match.HendersonPark'),
        ),
    ]
