# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill_match', '0003_hendersonpark_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.PositiveIntegerField()),
                ('sportsmanship', models.PositiveIntegerField()),
                ('availability', models.PositiveIntegerField()),
                ('punctuality', models.CharField(choices=[('No Show', 'No Show'), ('On Time', 'On Time'), ('Little bit late', 'Little bit late'), ('Late', 'Over 10 min late')], default='On Time', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('sport', models.CharField(choices=[('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Pickleball', 'Pickleball'), ('Other', 'Other')], default='Tennis', max_length=25)),
                ('other', models.CharField(blank=True, max_length=25, null=True)),
                ('skill_level', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Challenge', 'Challenge'), ('Joined', 'Joined'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Open', max_length=10)),
                ('img_url', models.URLField(default='http://res.cloudinary.com/skill-match/image/upload/v1451804013/trophy_200_cnaras.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_match.HendersonPark')),
                ('players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_match.Match'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
