# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_match', '0005_remove_feedback_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
