# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_match', '0006_match_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hendersonpark',
            old_name='url',
            new_name='henderson_url',
        ),
    ]
